### PR TITLE
Example fix for the dynamic port "serialisation desync" problem.

### LINKED ISSUE #218: Major issue: changing constraints/types of dynamic port lists breaks internal serialisation
I'm not entirely sure how best to phrase this, but I'll do what I can. Setting up a dynamic port list of some type plus type constraints, then changing the constraint/array type later leads to a disconnect in internal port serialisation. New list elements will be given the new type/constraint (I believe), but existing dynamic ports built from list items will not be updated to reflect the new changes.

This is present in the current master version as well as in release 1.7 (I think).

**I believe this to be a crippling issue** and suggest addressing it ASAP; questions related to that, and how best to go about it, are in the conclusion of this report. 

### Example reproduction setup
Ingredients:
* two dummy classes
image

* inputs (on "target" node):
```csharp
[Input(typeConstraint = TypeConstraint.Strict)]
public float floatInput;

[Input(typeConstraint = TypeConstraint.Strict, dynamicPortList = true, connectionType = ConnectionType.Override)]
public Derived[] derivedInputs;
```

* outputs (on "source" node):
```csharp
[Output(typeConstraint = TypeConstraint.None, dynamicPortList = true, connectionType = ConnectionType.Override)]
public Base[] baseOutputs;

[Output(typeConstraint = TypeConstraint.None, connectionType = ConnectionType.Override)]
public Base baseOutput;
```

We use two nodes: "source" , which houses outputs, and "target", where the aforelisted inputs are. 

### Type constraints
Observing the port data as listed in the node's Inspector, one notices that dynamic ports don't actually inherit type constraints or connection type settings (or if they do, changing those in the attribute will cause them to not be updated to the new values). (The non-dynamic port is always serialised correctly.)
image

**Note** however that the "array port" (port named after the field itself) is serialised properly after any changes, and only the dynamic fields are not.

### Types
What's even worse, when changing the field type of a dynamic port list, e.g. the array of "baseOutputs" from `Base[]` to `string[]`, existing array elements (or rather, their dynamic port definitions) will not update their underlying type references, even though the underlying properties themselves will be of the new type.

With the aforementioned modification
```csharp
[Output(typeConstraint = TypeConstraint.None, dynamicPortList = true, connectionType = ConnectionType.Override)]
public string[] baseOutputs;
```
we can see the Inspector data mismatch (though again we confirm that a non-dynamic port will always be serialised properly):
image
The existing first entry maintains its old port type, even though the field type has changed; new entries obey the new restrictions.

Again, **note** that the "array port" itself is also serialised properly.

### Result
Visually, both aspects of this issue can be seen here:
image
Even though we explicitly forbid multiple connections to our inputs and give them strict type constraints, this can still happen; and even though `baseOutputs` is a string array now, its first element, still considered to be of type `Base`, has its handle drawn in a different colour and is considered to belong to its former type.

### How do we fix it?
I've only been poking at xNode for the last 2-3 days, so I can't consider myself terribly in the know about it. Still, I see ~two~ three lines of thought for fixing this particular issue:

* Make sure any update to the backing field/attribute reserialises dynamic ports properly. Given that the "array port" is updated accordingly, enforcing the same for dynamic ports shouldn't be too difficult;
* "Slave" all dynamic entries to the "array port". In other words, when checking constraints/types for dynamic ports refers to their "array port". This sounds like it could be troublesome in more ways than one, but then again, I haven't yet looked into how dynamic ports are actually accessed and how they "store" their values.
* Given #221, eliminate two birds with one stone by setting the dynamic port types to the backing array's element type. I don't know whether this would break something else though.

I'd be happy to look into fixing this after I investigate the causes behind #217 (which, I hope, should be trivial to fix after I look into how the dragging stuff actually works), but I'd appreciate any suggestions as to how would be best to proceed about this.

### PR DESCRIPTION
**Pull request by LumosX**
Fixes #218 -- perhaps. This pull request contains an example fix for the issue. The node cache's "update ports" method is extended to take dynamic ports into account, and this is also invoked whenever a list of dynamic ports is redrawn. There's probably a more efficient way to do it, but it gets the job done and fixes any and all issues outlined before.

Note that I've not tested it much (if only we had a test suite of some sort, haha), and especially not with lists of dynamic ports without an array/list backing value. I still don't see the point of those and they don't seem to work half the time.

Please have a look and maybe check it out. I'm not sure if it's exactly what it should be.

No fancy C# 6/7 features used, so this should be as backwards-compatible as necessary.

### CODE REVIEW

File: Scripts/Node.cs [hunk 1]
```diff
@@ -119,12 +119,12 @@ public enum TypeConstraint {
...
             if (graphHotfix != null) graph = graphHotfix;
             graphHotfix = null;
-            UpdateStaticPorts();
+            UpdatePorts();
             Init();
         }
 
-        /// <summary> Update static ports to reflect class fields. This happens automatically on enable. </summary>
-        public void UpdateStaticPorts() {
+        /// <summary> Update all ports to reflect class fields. This happens automatically on enable or on redrawing the list of ports. </summary>
```
Comment (Siccity) [inline Scripts/Node.cs]: Does not update *all* ports. It updates static ports and dynamic ports managed by DynamicPortList.

File: Scripts/NodeDataCache.cs [hunk 2]
```diff
@@ -9,14 +10,16 @@ public static class NodeDataCache {
         private static PortDataCache portDataCache;
         private static bool Initialized { get { return portDataCache != null; } }
 
-        /// <summary> Update static ports to reflect class fields. </summary>
+        /// <summary> Update static and dynamic ports to reflect class fields. </summary>
```
Comment (Siccity) [inline Scripts/NodeDataCache.cs]: Only dynamic ports managed by DynamicPortList

File: Scripts/NodeDataCache.cs [hunk 3]
```diff
@@ -60,6 +68,31 @@ public static class NodeDataCache {
...
                 }
             }
+            
+            // Finally, make sure dynamic port settings correspond to the settings of their backing field
+            foreach (NodePort dynamicPort in dynamicPorts) {
+                string[] parts = dynamicPort.fieldName.Split(' ');
+                if (parts.Length != 2) {
+                    Debug.LogError("Dynamic port name " + dynamicPort.fieldName + " is invalid.");
+                    continue;
+                }
```
Comment (Siccity) [inline Scripts/NodeDataCache.cs]: Not an error. Not all dynamic ports are used by DynamicPortList

File: Scripts/NodeDataCache.cs [hunk 4]
```diff
@@ -150,5 +183,10 @@ private class PortDataCache : Dictionary<System.Type, List<NodePort>>, ISerializ
                     this.Add(keys[i], values[i]);
             }
         }
+
+        [MenuItem("TOOLS/LOL")]
+        public static void LOL() {
+            portDataCache = null;
+        }
```
Comment (Siccity) [inline Scripts/NodeDataCache.cs]: Leads to belly cramps when invoked too many times. Perhaps we should lay it off for now.

File: Scripts/NodeDataCache.cs (hunk 3 above)
Comment (Siccity) [reply Scripts/NodeDataCache.cs]: Also bear in mind that a port can technically be named "myField 2" on a node with a valid `myField` variable *without* `myField` being a DynamicPortList. So you have to verify that `myField` is in fact a DynamicPortList before making any changes to the port.

File: Scripts/NodePort.cs [hunk 5]
```diff
@@ -19,9 +19,22 @@ public enum IO { Input, Output }
             }
         }
 
-        public IO direction { get { return _direction; } }
-        public Node.ConnectionType connectionType { get { return _connectionType; } }
-        public Node.TypeConstraint typeConstraint { get { return _typeConstraint; } }
+        // public IO direction { get { return _direction; } }
+        // public Node.ConnectionType connectionType { get { return _connectionType; } }
+        // public Node.TypeConstraint typeConstraint { get { return _typeConstraint; } }
```
Comment (Siccity) [inline Scripts/NodePort.cs]: This is git. We don't want any commented code.

File: Scripts/NodeDataCache.cs [hunk 6]
```diff
@@ -60,6 +68,31 @@ public static class NodeDataCache {
...
+                if (!staticPorts.TryGetValue(backingPortName, out backingPort)) {
+                    Debug.LogError($"Could not find backing port \"{backingPortName}\" for port {dynamicPort.fieldName}");
+                    continue;
+                }
+                
+                // Update port constraints. Creating a new port instead will break the editor, mandating the need for setters.
+                dynamicPort.ValueType = backingPort.ValueType;
+                dynamicPort.direction = backingPort.direction;
+                dynamicPort.connectionType = backingPort.connectionType;
+                dynamicPort.typeConstraint = backingPort.typeConstraint;
```
Comment (Siccity) [inline Scripts/NodeDataCache.cs]: I think you're on the right track with this part.

File: Scripts/NodeDataCache.cs [hunk 7]
```diff
@@ -60,6 +68,31 @@ public static class NodeDataCache {
...
+                if (parts.Length != 2) {
+                    Debug.LogError("Dynamic port name " + dynamicPort.fieldName + " is invalid.");
+                    continue;
+                }
+                string backingPortName = parts[0];
+                NodePort backingPort;
+                if (!staticPorts.TryGetValue(backingPortName, out backingPort)) {
+                    Debug.LogError($"Could not find backing port \"{backingPortName}\" for port {dynamicPort.fieldName}");
+                    continue;
+                }
```
Comment (Siccity) [inline Scripts/NodeDataCache.cs]: This static "backing port" you got here is actually an unwanted side effect, as it is not used for anything. Using it here to your advantage is pretty smart.

File: Scripts/Node.cs (hunk 1 above)
Comment (LumosX) [reply Scripts/Node.cs]: Noted, completely forgot that non-list-based dynamic ports have to be drawn manually and thus won't be covered by the dynamic port list drawer.

File: Scripts/NodeDataCache.cs (hunk 4 above)
Comment (LumosX) [reply Scripts/NodeDataCache.cs]: This is an oversight; I was using this to poke around the cache rebuilding method more easily for informative purposes, but I shouldn't have forgotten to delete this method entirely...

File: Scripts/NodePort.cs (hunk 5 above)
Comment (LumosX) [reply Scripts/NodePort.cs]: I know, and this is a blatant oversight on my part. How embarrassing... 😅

Comment (LumosX) [reply Scripts/NodePort.cs]: Now removed.

File: Scripts/NodeDataCache.cs (hunk 4 above)
Comment (LumosX) [reply Scripts/NodeDataCache.cs]: Now removed.

File: Scripts/NodeDataCache.cs (hunk 3 above)
Comment (LumosX) [reply Scripts/NodeDataCache.cs]: Proper verification for dynamic list ports is now in place, though I'd appreciate having it reviewed.

File: Scripts/NodeDataCache.cs (hunk 2 above)
Comment (LumosX) [reply Scripts/NodeDataCache.cs]: Now fixed.

File: Scripts/Node.cs (hunk 1 above)
Comment (LumosX) [reply Scripts/Node.cs]: Now fixed.

**Comment by LumosX** [comment]
All respective changes have been implemented. I'd appreciate a review of my verification of dynamic list ports though.

On a side note, what's the motivation for allowing multiple `Input` or `Output` attributes on one field?

**Comment by Siccity** [comment]
Is that allowed? Not sure.

**Comment by LumosX** [comment]
Well, both attributes have `AllowMultiple = true` is what I meant, and I wasn't sure whether that's necessary for anything. In practice the last defined attribute seems to be used to generate the actual port.

**Comment by Siccity** [comment]
According to git blame, that option has been set on both attributes since the first version of that port system. I think it's safe to remove it.

**Comment by Siccity** [comment]
Tested with non-array types.
```cs
[Output(dynamicPortList = true)]public float a;
[Output(dynamicPortList = true)]public float[] b;
```
Added some items and switched both fields to `string`
image

**Comment by LumosX** [comment]
This is caused because a serialised property of type `string` technically is an array of type `char`, even though that array is empty in this particular case...
The fastest patch, off the top of my head, is to add an array size check line 343 of NodeEditorGUILayout such as:
```csharp
if (hasArrayData && arrayData.arraySize > 0) {
```
However I'm not sure this won't cause any side effects. I'll look into it further.

**Comment by LumosX** [comment]
The same bug occurs on master right now. I guess that without the auto-type fixing we're working on here, it'd just be harder to spot or something.

I've pushed another commit that resolves this by explicitly excluding strings from the array types. I think that's the safer approach.

Example:
image

On Target:
```csharp
[Input(typeConstraint = TypeConstraint.Strict)]
public string[] stringArray;

[Input(typeConstraint = TypeConstraint.Strict)]
public string stringInput1;

[Input(typeConstraint = TypeConstraint.Strict)]
public string stringInput2;
```

On Source (testing purposes only, I've got my testing nodes in another project altogether)
```csharp
[Output(typeConstraint = TypeConstraint.Strict, dynamicPortList = true, connectionType = ConnectionType.Override)]
public string baseOutputs;

[Output(typeConstraint = TypeConstraint.Strict, dynamicPortList = true, connectionType = ConnectionType.Override)]
public string[] floatOutputs;

public override object GetValue(NodePort port) {
	var n = port.fieldName.Split(' ');
	if (n[0] == "baseOutputs") return "fake " + n[1];
	
	for (var i = 0; i < (floatOutputs?.Length ?? 0); i++) {
		if (port.fieldName == $"floatOutputs {i}") return floatOutputs?[i];
	}
	
	return null;
}
```
P.S.: I almost feel like xNode should ship with some helper method that reduces all the boilerplate around handling dynamic ports... such as something like [what we use in-house](https://gist.github.com/LumosX/9cde05c46956fbc705dcbb2d9b39e087).
